### **Introduction to Numpy**

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
a = np.array ([1,2,3,4])
a

array([1, 2, 3, 4])

In [8]:
a[2]

np.int64(3)

In [9]:
a[2] = 10
a

array([ 1,  2, 10,  4])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [12]:
np.linspace(0,1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [13]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
n         

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
n[0,1]

np.int64(2)

In [18]:
n[0,1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [19]:
n[1]

array([4, 5, 6])

In [20]:
n[2] = [1,1,1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [22]:
n[:, 1]

array([20,  5,  1])

In [27]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [28]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [30]:
np.random.seed(2)
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [31]:
np.random.seed(2)
np.random.randint(low=0, high=100, size = (5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [32]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [33]:
a + 1

array([1, 2, 3, 4, 5])

In [35]:
a * 2

array([0, 2, 4, 6, 8])

In [36]:
a -1 

array([-1,  0,  1,  2,  3])

In [38]:
b = 10 + (a*2)
b

array([10, 12, 14, 16, 18])

In [39]:
a + b

array([10, 13, 16, 19, 22])

In [40]:
a >= 2

array([False, False,  True,  True,  True])

In [41]:
a > b

array([False, False, False, False, False])

In [42]:
a[a>b]

array([], dtype=int64)

In [43]:
a.min()

np.int64(0)

In [44]:
a.max()

np.int64(4)

In [45]:
a.mean()

np.float64(2.0)

In [46]:
a.sum()

np.int64(10)